// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: msgservice.proto

package msgservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAttachmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentRequest) Reset() {
	*x = GetAttachmentRequest{}
	mi := &file_msgservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentRequest) ProtoMessage() {}

func (x *GetAttachmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentRequest.ProtoReflect.Descriptor instead.
func (*GetAttachmentRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttachmentRequest) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

type GetAttachmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileUrl       string                 `protobuf:"bytes,4,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttachmentResponse) Reset() {
	*x = GetAttachmentResponse{}
	mi := &file_msgservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttachmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttachmentResponse) ProtoMessage() {}

func (x *GetAttachmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttachmentResponse.ProtoReflect.Descriptor instead.
func (*GetAttachmentResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetAttachmentResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetAttachmentResponse) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *GetAttachmentResponse) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *GetAttachmentResponse) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type AddParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantResponse) Reset() {
	*x = AddParticipantResponse{}
	mi := &file_msgservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantResponse) ProtoMessage() {}

func (x *AddParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantResponse.ProtoReflect.Descriptor instead.
func (*AddParticipantResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{2}
}

func (x *AddParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddParticipantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddParticipantRequest) Reset() {
	*x = AddParticipantRequest{}
	mi := &file_msgservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantRequest) ProtoMessage() {}

func (x *AddParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{3}
}

func (x *AddParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddParticipantRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteParticipantRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteParticipantRequest) Reset() {
	*x = DeleteParticipantRequest{}
	mi := &file_msgservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParticipantRequest) ProtoMessage() {}

func (x *DeleteParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParticipantRequest.ProtoReflect.Descriptor instead.
func (*DeleteParticipantRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteParticipantRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type DeleteParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteParticipantResponse) Reset() {
	*x = DeleteParticipantResponse{}
	mi := &file_msgservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteParticipantResponse) ProtoMessage() {}

func (x *DeleteParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteParticipantResponse.ProtoReflect.Descriptor instead.
func (*DeleteParticipantResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListConversationsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	AfterTimestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=after_timestamp,json=afterTimestamp,proto3" json:"after_timestamp,omitempty"`
	BeforeTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"`
	ReversedOrder   bool                   `protobuf:"varint,5,opt,name=reversed_order,json=reversedOrder,proto3" json:"reversed_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_msgservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListConversationsRequest) GetAfterTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AfterTimestamp
	}
	return nil
}

func (x *ListConversationsRequest) GetBeforeTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BeforeTimestamp
	}
	return nil
}

func (x *ListConversationsRequest) GetReversedOrder() bool {
	if x != nil {
		return x.ReversedOrder
	}
	return false
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	NextOffset    int32                                     `protobuf:"varint,1,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	Conversations []*ListConversationsResponse_Conversation `protobuf:"bytes,2,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_msgservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{7}
}

func (x *ListConversationsResponse) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *ListConversationsResponse) GetConversations() []*ListConversationsResponse_Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type GetConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_msgservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{8}
}

func (x *GetConversationRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId      string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedDate    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,4,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_msgservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{9}
}

func (x *GetConversationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetConversationResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *GetConversationResponse) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *GetConversationResponse) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type CreateConversationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId      string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,3,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_msgservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{10}
}

func (x *CreateConversationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConversationRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *CreateConversationRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type CreateConversationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	CreatedDate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_msgservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{11}
}

func (x *CreateConversationResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *CreateConversationResponse) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

type DeleteAttachmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  []string               `protobuf:"bytes,1,rep,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentsRequest) Reset() {
	*x = DeleteAttachmentsRequest{}
	mi := &file_msgservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentsRequest) ProtoMessage() {}

func (x *DeleteAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAttachmentsRequest) GetAttachmentId() []string {
	if x != nil {
		return x.AttachmentId
	}
	return nil
}

type DeleteAttachmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAttachmentsResponse) Reset() {
	*x = DeleteAttachmentsResponse{}
	mi := &file_msgservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAttachmentsResponse) ProtoMessage() {}

func (x *DeleteAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{13}
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	MessageBody   string                 `protobuf:"bytes,2,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_msgservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{14}
}

func (x *EditMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EditMessageRequest) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

type EditMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageResponse) Reset() {
	*x = EditMessageResponse{}
	mi := &file_msgservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResponse) ProtoMessage() {}

func (x *EditMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResponse.ProtoReflect.Descriptor instead.
func (*EditMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{15}
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_msgservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_msgservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{17}
}

type ListMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	AfterTimestamp  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=after_timestamp,json=afterTimestamp,proto3" json:"after_timestamp,omitempty"`
	BeforeTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=before_timestamp,json=beforeTimestamp,proto3" json:"before_timestamp,omitempty"`
	ReversedOrder   bool                   `protobuf:"varint,5,opt,name=reversed_order,json=reversedOrder,proto3" json:"reversed_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_msgservice_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{18}
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMessagesRequest) GetAfterTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AfterTimestamp
	}
	return nil
}

func (x *ListMessagesRequest) GetBeforeTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.BeforeTimestamp
	}
	return nil
}

func (x *ListMessagesRequest) GetReversedOrder() bool {
	if x != nil {
		return x.ReversedOrder
	}
	return false
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	NextOffset    int32                           `protobuf:"varint,1,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	Messages      []*ListMessagesResponse_Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_msgservice_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{19}
}

func (x *ListMessagesResponse) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

func (x *ListMessagesResponse) GetMessages() []*ListMessagesResponse_Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_msgservice_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{20}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageBody    string                 `protobuf:"bytes,3,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	Attachments    []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_msgservice_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{21}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SendMessageRequest) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

func (x *SendMessageRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_msgservice_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{22}
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageBody    string                 `protobuf:"bytes,4,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	Updated        bool                   `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Attachments    []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_msgservice_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{23}
}

func (x *GetMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetMessageResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *GetMessageResponse) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

func (x *GetMessageResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *GetMessageResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *GetMessageResponse) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachmentId  string                 `protobuf:"bytes,1,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_msgservice_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{24}
}

func (x *Attachment) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Attachment) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Attachment) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

type ListConversationsResponse_Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatorId      string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,5,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConversationsResponse_Conversation) Reset() {
	*x = ListConversationsResponse_Conversation{}
	mi := &file_msgservice_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse_Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse_Conversation) ProtoMessage() {}

func (x *ListConversationsResponse_Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse_Conversation.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse_Conversation) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListConversationsResponse_Conversation) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListConversationsResponse_Conversation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListConversationsResponse_Conversation) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *ListConversationsResponse_Conversation) GetCreatedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedDate
	}
	return nil
}

func (x *ListConversationsResponse_Conversation) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type ListMessagesResponse_Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MessageBody    string                 `protobuf:"bytes,4,opt,name=message_body,json=messageBody,proto3" json:"message_body,omitempty"`
	Edited         bool                   `protobuf:"varint,5,opt,name=edited,proto3" json:"edited,omitempty"`
	SentAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Attachments    []*Attachment          `protobuf:"bytes,7,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesResponse_Message) Reset() {
	*x = ListMessagesResponse_Message{}
	mi := &file_msgservice_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse_Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse_Message) ProtoMessage() {}

func (x *ListMessagesResponse_Message) ProtoReflect() protoreflect.Message {
	mi := &file_msgservice_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse_Message.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse_Message) Descriptor() ([]byte, []int) {
	return file_msgservice_proto_rawDescGZIP(), []int{19, 0}
}

func (x *ListMessagesResponse_Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ListMessagesResponse_Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessagesResponse_Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ListMessagesResponse_Message) GetMessageBody() string {
	if x != nil {
		return x.MessageBody
	}
	return ""
}

func (x *ListMessagesResponse_Message) GetEdited() bool {
	if x != nil {
		return x.Edited
	}
	return false
}

func (x *ListMessagesResponse_Message) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ListMessagesResponse_Message) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

var File_msgservice_proto protoreflect.FileDescriptor

const file_msgservice_proto_rawDesc = "" +
	"\n" +
	"\x10msgservice.proto\x12\n" +
	"msgservice\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x14GetAttachmentRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\"\x89\x01\n" +
	"\x15GetAttachmentResponse\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x19\n" +
	"\bfile_url\x18\x04 \x01(\tR\afileUrl\"2\n" +
	"\x16AddParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x15AddParticipantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\\\n" +
	"\x18DeleteParticipantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"5\n" +
	"\x19DeleteParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xfb\x01\n" +
	"\x18ListConversationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12C\n" +
	"\x0fafter_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eafterTimestamp\x12E\n" +
	"\x10before_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fbeforeTimestamp\x12%\n" +
	"\x0ereversed_order\x18\x05 \x01(\bR\rreversedOrder\"\xeb\x02\n" +
	"\x19ListConversationsResponse\x12\x1f\n" +
	"\vnext_offset\x18\x01 \x01(\x05R\n" +
	"nextOffset\x12X\n" +
	"\rconversations\x18\x02 \x03(\v22.msgservice.ListConversationsResponse.ConversationR\rconversations\x1a\xd2\x01\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\tR\tcreatorId\x12=\n" +
	"\fcreated_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\x12'\n" +
	"\x0fparticipant_ids\x18\x05 \x03(\tR\x0eparticipantIds\"A\n" +
	"\x16GetConversationRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\xb4\x01\n" +
	"\x17GetConversationResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12=\n" +
	"\fcreated_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\x12'\n" +
	"\x0fparticipant_ids\x18\x04 \x03(\tR\x0eparticipantIds\"w\n" +
	"\x19CreateConversationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\tR\tcreatorId\x12'\n" +
	"\x0fparticipant_ids\x18\x03 \x03(\tR\x0eparticipantIds\"\x84\x01\n" +
	"\x1aCreateConversationResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12=\n" +
	"\fcreated_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcreatedDate\"?\n" +
	"\x18DeleteAttachmentsRequest\x12#\n" +
	"\rattachment_id\x18\x01 \x03(\tR\fattachmentId\"\x1b\n" +
	"\x19DeleteAttachmentsResponse\"V\n" +
	"\x12EditMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12!\n" +
	"\fmessage_body\x18\x02 \x01(\tR\vmessageBody\"\x15\n" +
	"\x13EditMessageResponse\"5\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x17\n" +
	"\x15DeleteMessageResponse\"\xf6\x01\n" +
	"\x13ListMessagesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12C\n" +
	"\x0fafter_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eafterTimestamp\x12E\n" +
	"\x10before_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fbeforeTimestamp\x12%\n" +
	"\x0ereversed_order\x18\x05 \x01(\bR\rreversedOrder\"\x98\x03\n" +
	"\x14ListMessagesResponse\x12\x1f\n" +
	"\vnext_offset\x18\x01 \x01(\x05R\n" +
	"nextOffset\x12D\n" +
	"\bmessages\x18\x02 \x03(\v2(.msgservice.ListMessagesResponse.MessageR\bmessages\x1a\x98\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12!\n" +
	"\fmessage_body\x18\x04 \x01(\tR\vmessageBody\x12\x16\n" +
	"\x06edited\x18\x05 \x01(\bR\x06edited\x123\n" +
	"\asent_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x128\n" +
	"\vattachments\x18\a \x03(\v2\x16.msgservice.AttachmentR\vattachments\"i\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"\xb7\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12!\n" +
	"\fmessage_body\x18\x03 \x01(\tR\vmessageBody\x128\n" +
	"\vattachments\x18\x04 \x03(\v2\x16.msgservice.AttachmentR\vattachments\"2\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xa5\x02\n" +
	"\x12GetMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12!\n" +
	"\fmessage_body\x18\x04 \x01(\tR\vmessageBody\x12\x18\n" +
	"\aupdated\x18\x05 \x01(\bR\aupdated\x123\n" +
	"\asent_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x128\n" +
	"\vattachments\x18\a \x03(\v2\x16.msgservice.AttachmentR\vattachments\"\xa3\x01\n" +
	"\n" +
	"Attachment\x12#\n" +
	"\rattachment_id\x18\x01 \x01(\tR\fattachmentId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl2\xb8\b\n" +
	"\n" +
	"MsgService\x12N\n" +
	"\vSendMessage\x12\x1e.msgservice.SendMessageRequest\x1a\x1f.msgservice.SendMessageResponse\x12K\n" +
	"\n" +
	"GetMessage\x12\x1d.msgservice.GetMessageRequest\x1a\x1e.msgservice.GetMessageResponse\x12Q\n" +
	"\fListMessages\x12\x1f.msgservice.ListMessagesRequest\x1a .msgservice.ListMessagesResponse\x12T\n" +
	"\rDeleteMessage\x12 .msgservice.DeleteMessageRequest\x1a!.msgservice.DeleteMessageResponse\x12N\n" +
	"\vEditMessage\x12\x1e.msgservice.EditMessageRequest\x1a\x1f.msgservice.EditMessageResponse\x12T\n" +
	"\rGetAttachment\x12 .msgservice.GetAttachmentRequest\x1a!.msgservice.GetAttachmentResponse\x12`\n" +
	"\x11DeleteAttachments\x12$.msgservice.DeleteAttachmentsRequest\x1a%.msgservice.DeleteAttachmentsResponse\x12c\n" +
	"\x12CreateConversation\x12%.msgservice.CreateConversationRequest\x1a&.msgservice.CreateConversationResponse\x12Z\n" +
	"\x0fGetConversation\x12\".msgservice.GetConversationRequest\x1a#.msgservice.GetConversationResponse\x12`\n" +
	"\x11ListConversations\x12$.msgservice.ListConversationsRequest\x1a%.msgservice.ListConversationsResponse\x12W\n" +
	"\x0eAddParticipant\x12!.msgservice.AddParticipantRequest\x1a\".msgservice.AddParticipantResponse\x12`\n" +
	"\x11DeleteParticipant\x12$.msgservice.DeleteParticipantRequest\x1a%.msgservice.DeleteParticipantResponseB\rZ\vmsgservice/b\x06proto3"

var (
	file_msgservice_proto_rawDescOnce sync.Once
	file_msgservice_proto_rawDescData []byte
)

func file_msgservice_proto_rawDescGZIP() []byte {
	file_msgservice_proto_rawDescOnce.Do(func() {
		file_msgservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msgservice_proto_rawDesc), len(file_msgservice_proto_rawDesc)))
	})
	return file_msgservice_proto_rawDescData
}

var file_msgservice_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_msgservice_proto_goTypes = []any{
	(*GetAttachmentRequest)(nil),                   // 0: msgservice.GetAttachmentRequest
	(*GetAttachmentResponse)(nil),                  // 1: msgservice.GetAttachmentResponse
	(*AddParticipantResponse)(nil),                 // 2: msgservice.AddParticipantResponse
	(*AddParticipantRequest)(nil),                  // 3: msgservice.AddParticipantRequest
	(*DeleteParticipantRequest)(nil),               // 4: msgservice.DeleteParticipantRequest
	(*DeleteParticipantResponse)(nil),              // 5: msgservice.DeleteParticipantResponse
	(*ListConversationsRequest)(nil),               // 6: msgservice.ListConversationsRequest
	(*ListConversationsResponse)(nil),              // 7: msgservice.ListConversationsResponse
	(*GetConversationRequest)(nil),                 // 8: msgservice.GetConversationRequest
	(*GetConversationResponse)(nil),                // 9: msgservice.GetConversationResponse
	(*CreateConversationRequest)(nil),              // 10: msgservice.CreateConversationRequest
	(*CreateConversationResponse)(nil),             // 11: msgservice.CreateConversationResponse
	(*DeleteAttachmentsRequest)(nil),               // 12: msgservice.DeleteAttachmentsRequest
	(*DeleteAttachmentsResponse)(nil),              // 13: msgservice.DeleteAttachmentsResponse
	(*EditMessageRequest)(nil),                     // 14: msgservice.EditMessageRequest
	(*EditMessageResponse)(nil),                    // 15: msgservice.EditMessageResponse
	(*DeleteMessageRequest)(nil),                   // 16: msgservice.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),                  // 17: msgservice.DeleteMessageResponse
	(*ListMessagesRequest)(nil),                    // 18: msgservice.ListMessagesRequest
	(*ListMessagesResponse)(nil),                   // 19: msgservice.ListMessagesResponse
	(*SendMessageResponse)(nil),                    // 20: msgservice.SendMessageResponse
	(*SendMessageRequest)(nil),                     // 21: msgservice.SendMessageRequest
	(*GetMessageRequest)(nil),                      // 22: msgservice.GetMessageRequest
	(*GetMessageResponse)(nil),                     // 23: msgservice.GetMessageResponse
	(*Attachment)(nil),                             // 24: msgservice.Attachment
	(*ListConversationsResponse_Conversation)(nil), // 25: msgservice.ListConversationsResponse.Conversation
	(*ListMessagesResponse_Message)(nil),           // 26: msgservice.ListMessagesResponse.Message
	(*timestamppb.Timestamp)(nil),                  // 27: google.protobuf.Timestamp
}
var file_msgservice_proto_depIdxs = []int32{
	27, // 0: msgservice.ListConversationsRequest.after_timestamp:type_name -> google.protobuf.Timestamp
	27, // 1: msgservice.ListConversationsRequest.before_timestamp:type_name -> google.protobuf.Timestamp
	25, // 2: msgservice.ListConversationsResponse.conversations:type_name -> msgservice.ListConversationsResponse.Conversation
	27, // 3: msgservice.GetConversationResponse.created_date:type_name -> google.protobuf.Timestamp
	27, // 4: msgservice.CreateConversationResponse.created_date:type_name -> google.protobuf.Timestamp
	27, // 5: msgservice.ListMessagesRequest.after_timestamp:type_name -> google.protobuf.Timestamp
	27, // 6: msgservice.ListMessagesRequest.before_timestamp:type_name -> google.protobuf.Timestamp
	26, // 7: msgservice.ListMessagesResponse.messages:type_name -> msgservice.ListMessagesResponse.Message
	27, // 8: msgservice.SendMessageResponse.sent_at:type_name -> google.protobuf.Timestamp
	24, // 9: msgservice.SendMessageRequest.attachments:type_name -> msgservice.Attachment
	27, // 10: msgservice.GetMessageResponse.sent_at:type_name -> google.protobuf.Timestamp
	24, // 11: msgservice.GetMessageResponse.attachments:type_name -> msgservice.Attachment
	27, // 12: msgservice.ListConversationsResponse.Conversation.created_date:type_name -> google.protobuf.Timestamp
	27, // 13: msgservice.ListMessagesResponse.Message.sent_at:type_name -> google.protobuf.Timestamp
	24, // 14: msgservice.ListMessagesResponse.Message.attachments:type_name -> msgservice.Attachment
	21, // 15: msgservice.MsgService.SendMessage:input_type -> msgservice.SendMessageRequest
	22, // 16: msgservice.MsgService.GetMessage:input_type -> msgservice.GetMessageRequest
	18, // 17: msgservice.MsgService.ListMessages:input_type -> msgservice.ListMessagesRequest
	16, // 18: msgservice.MsgService.DeleteMessage:input_type -> msgservice.DeleteMessageRequest
	14, // 19: msgservice.MsgService.EditMessage:input_type -> msgservice.EditMessageRequest
	0,  // 20: msgservice.MsgService.GetAttachment:input_type -> msgservice.GetAttachmentRequest
	12, // 21: msgservice.MsgService.DeleteAttachments:input_type -> msgservice.DeleteAttachmentsRequest
	10, // 22: msgservice.MsgService.CreateConversation:input_type -> msgservice.CreateConversationRequest
	8,  // 23: msgservice.MsgService.GetConversation:input_type -> msgservice.GetConversationRequest
	6,  // 24: msgservice.MsgService.ListConversations:input_type -> msgservice.ListConversationsRequest
	3,  // 25: msgservice.MsgService.AddParticipant:input_type -> msgservice.AddParticipantRequest
	4,  // 26: msgservice.MsgService.DeleteParticipant:input_type -> msgservice.DeleteParticipantRequest
	20, // 27: msgservice.MsgService.SendMessage:output_type -> msgservice.SendMessageResponse
	23, // 28: msgservice.MsgService.GetMessage:output_type -> msgservice.GetMessageResponse
	19, // 29: msgservice.MsgService.ListMessages:output_type -> msgservice.ListMessagesResponse
	17, // 30: msgservice.MsgService.DeleteMessage:output_type -> msgservice.DeleteMessageResponse
	15, // 31: msgservice.MsgService.EditMessage:output_type -> msgservice.EditMessageResponse
	1,  // 32: msgservice.MsgService.GetAttachment:output_type -> msgservice.GetAttachmentResponse
	13, // 33: msgservice.MsgService.DeleteAttachments:output_type -> msgservice.DeleteAttachmentsResponse
	11, // 34: msgservice.MsgService.CreateConversation:output_type -> msgservice.CreateConversationResponse
	9,  // 35: msgservice.MsgService.GetConversation:output_type -> msgservice.GetConversationResponse
	7,  // 36: msgservice.MsgService.ListConversations:output_type -> msgservice.ListConversationsResponse
	2,  // 37: msgservice.MsgService.AddParticipant:output_type -> msgservice.AddParticipantResponse
	5,  // 38: msgservice.MsgService.DeleteParticipant:output_type -> msgservice.DeleteParticipantResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_msgservice_proto_init() }
func file_msgservice_proto_init() {
	if File_msgservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msgservice_proto_rawDesc), len(file_msgservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msgservice_proto_goTypes,
		DependencyIndexes: file_msgservice_proto_depIdxs,
		MessageInfos:      file_msgservice_proto_msgTypes,
	}.Build()
	File_msgservice_proto = out.File
	file_msgservice_proto_goTypes = nil
	file_msgservice_proto_depIdxs = nil
}
