// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Usersdatum struct {
	UserID    uuid.UUID
	FirstName string
	LastName  pgtype.Text
	Email     pgtype.Text
	AvatarUrl pgtype.Text
}
