// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	AttachmentID uuid.UUID
	MessageID    uuid.UUID
	FileName     pgtype.Text
	FileType     pgtype.Text
	FileSize     pgtype.Int4
	FileUrl      pgtype.Text
}

type Conversation struct {
	ConversationID uuid.UUID
	Name           string
	CreationDate   pgtype.Timestamp
}

type Message struct {
	MessageID      uuid.UUID
	ConversationID uuid.UUID
	SenderID       uuid.UUID
	SentAt         pgtype.Timestamp
	MessageBody    pgtype.Text
}

type Participant struct {
	ParticipantID  uuid.UUID
	ConversationID uuid.UUID
	UserID         uuid.UUID
}
