// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	AttachmentID pgtype.UUID
	MessageID    pgtype.UUID
	FileName     pgtype.Text
	FileType     pgtype.Text
	FileSize     pgtype.Int4
	FileUrl      pgtype.Text
}

type Conversation struct {
	ConversationID pgtype.UUID
	Name           string
	CreationDate   pgtype.Timestamp
}

type Message struct {
	MessageID      pgtype.UUID
	ConversationID pgtype.UUID
	SenderID       pgtype.UUID
	SentAt         pgtype.Timestamp
	MessageBody    pgtype.Text
}

type Participant struct {
	ParticipantID  pgtype.UUID
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}
