// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID       pgtype.UUID
	Username     string
	Password     string
	RegisteredAt pgtype.Timestamp
}
